# Generated by Django 4.2.3 on 2025-05-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_borrow_returned_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
